rem JumpCutterUltra.exe --input_file MATLABReview04_BasicplottinginMATLAB.wmv.mp4 --sounded_speed 1 --silent_speed 9999999 --frame_margin 1 --output_file MATLABReview04_BasicplottinginMATLAB_cut2.mp4

rem youtube-dl -F -ci https://www.youtube.com/playlist?list=PL9YM1ktRDUJYBGMzHv3Qvjjf5Gf9dizzv



REM youtube-dl -f 22 -ci https://www.youtube.com/playlist?list=PL9YM1ktRDUJYBGMzHv3Qvjjf5Gf9dizzv
rem python rename.py
python rename_noNum.py
rem split long file and create a list of file that can be merged later
rem python split.py
rem python split_one.py

rem run jumcut for every split file
for %%f in (*.wmv) DO JumpCutterUltra.exe --input_file %%f --sounded_speed 1 --silent_speed 999999 --frame_margin 1 --output_file %%f_jcmg1.mp4

rem merge them using ffmpeg concat based on the .txt file generated by split.py script
python Generate_txt_2_merge.py
for %%f in (*.txt) DO ffmpeg -f concat -i %%f -c copy %%fsplit_cut_merged.mp4



